name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build base image
        run: docker build -t spotify_radio .

      - name: pytest
        run: docker run -w /app/tests spotify_radio python -m pytest

      - name: flake
        run: docker run spotify_radio python -m flake8
