name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build base image
        run: docker build -t spotify_radio .

  run_tests:
    runs-on: self-hosted
    needs: build_image

    steps:
      - name: pytest
        run: docker run -w /app/tests spotify_radio 'python -m pytest'

      - name: flake
        run: docker run spotify_radio 'python -m flake8'
